[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "sm_sequence_mapping_utils"
version = "1.2.3"
authors = [
  { name="Steven Marshall", email="stevenmarshall@uvic.ca" },
]
description = "Utilities for mapping sequences."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "biopython",
]

[project.urls]
Homepage = "https://github.com/StevenMarshallUVic/sequence-mapping-utils"
Issues = "https://github.com/StevenMarshallUVic/sequence-mapping-utils/issues"
